### ISSUE TITLE
Captcha is not showing on custom page

### ISSUE THREAD

**Issue by guptadeepika** [StudioForty9/Recaptcha#11]
Hi, 
i have added studioforty9 extension in one of my magento project.

I followed all the steps but the captcha is not showing
please se in attachment
![udqa](https://cloud.githubusercontent.com/assets/2841000/10357893/5505899a-6da5-11e5-887c-8d2933ceca47.JPG)

and added   <?php echo $this->getChildHtml('studioforty9.recaptcha.explicit'); ?> in phtml file.

Please reply asap.... it's urgent.

**Comment by eoghanobrien** [comment]
We offer paid support for custom integration work - http://www.studioforty9.com/paid-support
