### ISSUE TITLE
There was an error with the recaptcha code, please try again.

### ISSUE THREAD

**Issue by satrunner** [StudioForty9/Recaptcha#14]
when trying to use create an account form Magento 1.9.2.3 I get    "There was an error with the recaptcha code, please try again." Recaptcha does not load on the page even after all fields are filled out. If you press create it gives an error above.

**Comment by eoghanobrien** [comment]
Check your exception log `var/log/exception.log`, if you have an error in there, please post it here

**Comment by satrunner** [comment]
I do not have path var/log/exception.log file does not exist

**Comment by eoghanobrien** [comment]
You'll need to enable it in you configuration settings then

**Comment by satrunner** [comment]
I don
t have any settings under recaptcha in googleAPI pointing to error logging. Could you please give me some info regarding how to enable that ?

**Comment by eoghanobrien** [comment]
There are no error logging setting under the Google API section, you have to go to System -> Configuration -> Advanced -> Developer -> Log Settings -> Enabled = Yes.

Your var/log directory must also be writable.

**Comment by satrunner** [comment]
2015-12-02T12:04:31+00:00 DEBUG (7): Exception message: package with this name does not exist and cannot be set.
Trace: #0 /var/www/html/app/code/core/Mage/Core/Model/Abstract.php(316): Mage_Adminhtml_Model_System_Config_Backend_Design_Package->_beforeSave()
#1 /var/www/html/app/code/core/Mage/Core/Model/Resource/Transaction.php(151): Mage_Core_Model_Abstract->save()
#2 /var/www/html/app/code/core/Mage/Adminhtml/Model/Config/Data.php(206): Mage_Core_Model_Resource_Transaction->save()
#3 /var/www/html/app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(165): Mage_Adminhtml_Model_Config_Data->save()
#4 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_System_ConfigController->saveAction()
#5 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('save')
#6 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#7 /var/www/html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#8 /var/www/html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#9 /var/www/html/index.php(83): Mage::run('', 'store')
#10 {main}
2015-12-12T11:35:18+00:00 ERR (3): 
exception 'Zend_Mail_Transport_Exception' with message 'Unable to send mail. ' in /var/www/html/lib/Zend/Mail/Transport/Sendmail.php:137
Stack trace:
#0 /var/www/html/lib/Zend/Mail/Transport/Abstract.php(348): Zend_Mail_Transport_Sendmail->_sendMail()
#1 /var/www/html/lib/Zend/Mail.php(1194): Zend_Mail_Transport_Abstract->send(Object(Zend_Mail))
#2 /var/www/html/app/code/local/Rugento/Invoisejuristic/Model/Core/Email/Template.php(2): Zend_Mail->send()
#3 /var/www/html/app/code/core/Mage/Core/Model/Email/Template.php(508): Rugento_Invoisejuristic_Model_Core_Email_Template->send(Array, Array, Array)
#4 /var/www/html/app/code/core/Mage/Core/Model/Email/Template/Mailer.php(84): Mage_Core_Model_Email_Template->sendTransactional('sales_email_ord...', 'sales', Array, Array, Array, '1')
#5 /var/www/html/app/code/core/Mage/Sales/Model/Order.php(1356): Mage_Core_Model_Email_Template_Mailer->send()
#6 /var/www/html/app/code/core/Mage/Sales/Model/Order.php(1371): Mage_Sales_Model_Order->queueNewOrderEmail(true)
#7 /var/www/html/app/code/local/Rugento/Payment2/Model/Observer.php(2): Mage_Sales_Model_Order->sendNewOrderEmail()
#8 /var/www/html/app/code/core/Mage/Core/Model/App.php(1357): Rugento_Payment2_Model_Observer->sendEmail(Object(Varien_Event_Observer))
#9 /var/www/html/app/code/core/Mage/Core/Model/App.php(1336): Mage_Core_Model_App->_callObserverMethod(Object(Rugento_Alfabank_Model_Observer), 'sendEmail', Object(Varien_Event_Observer))
#10 /var/www/html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('checkout_submit...', Array)
#11 /var/www/html/app/code/core/Mage/Checkout/Model/Type/Onepage.php(873): Mage::dispatchEvent('checkout_submit...', Array)
#12 /var/www/html/app/code/core/Mage/Checkout/controllers/OnepageController.php(579): Mage_Checkout_Model_Type_Onepage->saveOrder()
#13 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->saveOrderAction()
#14 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#15 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#16 /var/www/html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#17 /var/www/html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#18 /var/www/html/index.php(83): Mage::run('', 'store')
#19 {main}
2016-01-21T09:01:09+00:00 ERR (3): 
exception 'Zend_Mail_Transport_Exception' with message 'Unable to send mail. ' in /var/www/html/lib/Zend/Mail/Transport/Sendmail.php:137
Stack trace:
#0 /var/www/html/lib/Zend/Mail/Transport/Abstract.php(348): Zend_Mail_Transport_Sendmail->_sendMail()
#1 /var/www/html/lib/Zend/Mail.php(1194): Zend_Mail_Transport_Abstract->send(Object(Zend_Mail))
#2 /var/www/html/app/code/local/Rugento/Invoisejuristic/Model/Core/Email/Template.php(2): Zend_Mail->send()
#3 /var/www/html/app/code/core/Mage/Core/Model/Email/Template.php(508): Rugento_Invoisejuristic_Model_Core_Email_Template->send('evbogachev@gmai...', NULL, Array)
#4 /var/www/html/app/code/core/Mage/Newsletter/Model/Subscriber.php(559): Mage_Core_Model_Email_Template->sendTransactional('newsletter_subs...', 'general', 'evbogachev@gmai...', NULL, Array)
#5 /var/www/html/app/code/core/Mage/Newsletter/Model/Subscriber.php(458): Mage_Newsletter_Model_Subscriber->sendConfirmationSuccessEmail()
#6 /var/www/html/app/code/core/Mage/Newsletter/Model/Observer.php(38): Mage_Newsletter_Model_Subscriber->subscribeCustomer(Object(Mage_Customer_Model_Customer))
#7 /var/www/html/app/code/core/Mage/Core/Model/App.php(1357): Mage_Newsletter_Model_Observer->subscribeCustomer(Object(Varien_Event_Observer))
#8 /var/www/html/app/code/core/Mage/Core/Model/App.php(1336): Mage_Core_Model_App->_callObserverMethod(Object(Mage_Newsletter_Model_Observer), 'subscribeCustom...', Object(Varien_Event_Observer))
#9 /var/www/html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('customer_save_a...', Array)
#10 /var/www/html/app/code/core/Mage/Core/Model/Abstract.php(466): Mage::dispatchEvent('customer_save_a...', Array)
#11 /var/www/html/app/code/core/Mage/Core/Model/Abstract.php(319): Mage_Core_Model_Abstract->_afterSave()
#12 /var/www/html/app/code/core/Mage/Customer/controllers/AccountController.php(301): Mage_Core_Model_Abstract->save()
#13 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->createPostAction()
#14 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('createpost')
#15 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#16 /var/www/html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#17 /var/www/html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#18 /var/www/html/index.php(83): Mage::run('', 'store')
#19 {main}
2016-01-21T09:01:09+00:00 ERR (3): 
exception 'Zend_Mail_Transport_Exception' with message 'Unable to send mail. ' in /var/www/html/lib/Zend/Mail/Transport/Sendmail.php:137
Stack trace:
#0 /var/www/html/lib/Zend/Mail/Transport/Abstract.php(348): Zend_Mail_Transport_Sendmail->_sendMail()
#1 /var/www/html/lib/Zend/Mail.php(1194): Zend_Mail_Transport_Abstract->send(Object(Zend_Mail))
#2 /var/www/html/app/code/local/Rugento/Invoisejuristic/Model/Core/Email/Template.php(2): Zend_Mail->send()
#3 /var/www/html/app/code/core/Mage/Core/Model/Email/Template.php(508): Rugento_Invoisejuristic_Model_Core_Email_Template->send(Array, Array, Array)
#4 /var/www/html/app/code/core/Mage/Core/Model/Email/Template/Mailer.php(84): Mage_Core_Model_Email_Template->sendTransactional('customer_create...', 'general', Array, Array, Array, '1')
#5 /var/www/html/app/code/core/Mage/Customer/Model/Customer.php(680): Mage_Core_Model_Email_Template_Mailer->send()
#6 /var/www/html/app/code/core/Mage/Customer/Model/Customer.php(607): Mage_Customer_Model_Customer->_sendEmailTemplate('customer/create...', 'customer/create...', Array, '1')
#7 /var/www/html/app/code/core/Mage/Customer/controllers/AccountController.php(575): Mage_Customer_Model_Customer->sendNewAccountEmail('registered', '', '1')
#8 /var/www/html/app/code/core/Mage/Customer/controllers/AccountController.php(350): Mage_Customer_AccountController->_welcomeCustomer(Object(Mage_Customer_Model_Customer))
#9 /var/www/html/app/code/core/Mage/Customer/controllers/AccountController.php(303): Mage_Customer_AccountController->_successProcessRegistration(Object(Mage_Customer_Model_Customer))
#10 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->createPostAction()
#11 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('createpost')
#12 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#13 /var/www/html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#14 /var/www/html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#15 /var/www/html/index.php(83): Mage::run('', 'store')
#16 {main}
2016-02-17T14:37:08+00:00 ERR (3): 
exception 'Zend_Mail_Transport_Exception' with message 'Unable to send mail. ' in /var/www/html/lib/Zend/Mail/Transport/Sendmail.php:137
Stack trace:
#0 /var/www/html/lib/Zend/Mail/Transport/Abstract.php(348): Zend_Mail_Transport_Sendmail->_sendMail()
#1 /var/www/html/lib/Zend/Mail.php(1194): Zend_Mail_Transport_Abstract->send(Object(Zend_Mail))
#2 /var/www/html/app/code/local/Rugento/Invoisejuristic/Model/Core/Email/Template.php(2): Zend_Mail->send()
#3 /var/www/html/app/code/core/Mage/Core/Model/Email/Template.php(508): Rugento_Invoisejuristic_Model_Core_Email_Template->send(Array, Array, Array)
#4 /var/www/html/app/code/core/Mage/Core/Model/Email/Template/Mailer.php(84): Mage_Core_Model_Email_Template->sendTransactional('sales_email_ord...', 'sales', Array, Array, Array, '1')
#5 /var/www/html/app/code/core/Mage/Sales/Model/Order.php(1354): Mage_Core_Model_Email_Template_Mailer->send()
#6 /var/www/html/app/code/core/Mage/Sales/Model/Order.php(1369): Mage_Sales_Model_Order->queueNewOrderEmail(true)
#7 /var/www/html/app/code/local/Rugento/Payment2/Model/Observer.php(2): Mage_Sales_Model_Order->sendNewOrderEmail()
#8 /var/www/html/app/code/core/Mage/Core/Model/App.php(1358): Rugento_Payment2_Model_Observer->sendEmail(Object(Varien_Event_Observer))
#9 /var/www/html/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Rugento_Alfabank_Model_Observer), 'sendEmail', Object(Varien_Event_Observer))
#10 /var/www/html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('checkout_submit...', Array)
#11 /var/www/html/app/code/core/Mage/Checkout/Model/Type/Onepage.php(873): Mage::dispatchEvent('checkout_submit...', Array)
#12 /var/www/html/app/code/core/Mage/Checkout/controllers/OnepageController.php(579): Mage_Checkout_Model_Type_Onepage->saveOrder()
#13 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->saveOrderAction()
#14 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#15 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#16 /var/www/html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#17 /var/www/html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#18 /var/www/html/index.php(83): Mage::run('', 'store')
#19 {main}
2016-02-17T14:39:05+00:00 ERR (3): 
exception 'Zend_Mail_Transport_Exception' with message 'Unable to send mail. ' in /var/www/html/lib/Zend/Mail/Transport/Sendmail.php:137
Stack trace:
#0 /var/www/html/lib/Zend/Mail/Transport/Abstract.php(348): Zend_Mail_Transport_Sendmail->_sendMail()
#1 /var/www/html/lib/Zend/Mail.php(1194): Zend_Mail_Transport_Abstract->send(Object(Zend_Mail))
#2 /var/www/html/app/code/local/Rugento/Invoisejuristic/Model/Core/Email/Template.php(2): Zend_Mail->send()
#3 /var/www/html/app/code/core/Mage/Core/Model/Email/Template.php(508): Rugento_Invoisejuristic_Model_Core_Email_Template->send(Array, Array, Array)
#4 /var/www/html/app/code/core/Mage/Core/Model/Email/Template/Mailer.php(84): Mage_Core_Model_Email_Template->sendTransactional('sales_email_inv...', 'sales', Array, Array, Array, '1')
#5 /var/www/html/app/code/core/Mage/Sales/Model/Order/Invoice.php(846): Mage_Core_Model_Email_Template_Mailer->send()
#6 /var/www/html/app/code/local/Rugento/Payment2/Model/Abstract.php(2): Mage_Sales_Model_Order_Invoice->sendEmail()
#7 /var/www/html/app/code/local/Rugento/Alfabank/Model/Payment.php(2): Rugento_Payment2_Model_Abstract->createInvoice()
#8 /var/www/html/app/code/local/Rugento/Alfabank/controllers/MerchantController.php(2): Rugento_Alfabank_Model_Payment->checkStatus()
#9 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Rugento_Alfabank_MerchantController->returnAction()
#10 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('return')
#11 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#12 /var/www/html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#13 /var/www/html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#14 /var/www/html/index.php(83): Mage::run('', 'store')
#15 {main}

There was an error with the recaptcha code, please try again.

**Comment by eoghanobrien** [comment]
It looks like you have a lot more problems than the recaptcha not working :(

All I'm interested in is an exception with recaptcha, can you just post that please. I need the stack trace.

**Comment by satrunner** [comment]
I posted everything I had in that file to show that there were no errors pertaining to recaptcha

**Comment by eoghanobrien** [comment]
So you're still getting `There was an error with the recaptcha code, please try again.`?
Which form are you submitting?

**Comment by satrunner** [comment]
https://shop.satrunner.ru/customer/account/create/  

Recaptcha does not even show up anymore

**Comment by eoghanobrien** [comment]
You'll need to check your template and Layout XML to get that going again

**Comment by satrunner** [comment]
Are you on upwork ?

**Comment by eoghanobrien** [comment]
No but StudioForty9 offer paid support at http://www.studioforty9.com/paid-support
