### ISSUE TITLE
Redirect to the current page

### ISSUE THREAD

**Issue by JelleGe** [StudioForty9/Recaptcha#16]
Hi,

I use a custom page to load the contact form, but when the form is submitted, your extension redirect to contacts/index/post/. But I want to redirect to the current page. So that it load my custom page.

How can I edit the redirect?

**Comment by eoghanobrien** [comment]
The extension doesn't redirect to contacts/index/post, that's the url to the controller action that processes the contact form, our extension will redirect to whatever page is in the `last_url` in your session but only when the reCAPTCHA fails verification.

It sounds like there's something else going wrong, more than likely it'll be to do with how you have set up your custom contact form.
