### ISSUE TITLE
'Unable to Connect to ssl://www.google.com:443. Error #0: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution

### ISSUE THREAD

**Issue by therofree** [StudioForty9/Recaptcha#23]
I am getting this error:
exception 'Zend_Http_Client_Adapter_Exception' with message 'Unable to Connect to ssl://www.google.com:443. Error #0: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution' in /public_html/lib/Zend/Http/Client/Adapter/Socket.php:235

**Comment by eoghanobrien** [comment]
It looks like a regression of #14. Since I don't have the problem and can't recreate it locally. Are you open to working through it here to see if it is actually a regression or just your environment?

**Comment by therofree** [comment]
It was an issue with the hosting.
