### ISSUE TITLE
Doesn't work on Fresh 1.9.3.1 Php 5.6

### ISSUE THREAD

**Issue by dwdonline** [StudioForty9/Recaptcha#27]
Are there any php requirements? I've installed it on a fresh Magento 1.9.3.1 and it doesn't work on any pages, or any of the default
<img width="1358" alt="screen shot 2016-12-09 at 5 05 18 pm" src="https://cloud.githubusercontent.com/assets/8183807/21069759/b945f056-be31-11e6-9f20-b9f2003c73e4.png">
 themes. Tried adding it manually and that doesn't worth either.

**Comment by strubloid** [comment]
![recaptcha](https://cloud.githubusercontent.com/assets/2131560/21141719/984749a6-c136-11e6-8680-cf5d8d65af8e.png)

Hello @dwdonline, I had tested in here using the Magento 1.9.3.1 and works, so you might see if you had configured correct your module, I am attaching a photo to try to explain how you can configure the module.

1 - Go to the Magento backend and click on System -> Google API;
2 - Click on the tab Google reCAPTCHA and change the option Enable to Yes;
3 - Now you will get 2 things to do, you need to generate the Site and Secret Keys, so you only need to click on the link "create a site key", you will be going to https://www.google.com/recaptcha/admin and over there you will generate the both keys, after that you only need to put those values inside of Site Key and Secret Key input;
4 - Now you need to select what is the place that you need the captcha be enabled, in this image I just selected them all, but you can choose between Contact Form, Product review Form, Account registration Form, Send to Friend Forma, Login Form and Forgot Password Form;
5 - And save the config.

If you can't see the Google reCAPTCHA tab you might need to flush all caches, logout and login again. 

Let me know if everything works well!
