### ISSUE TITLE
Captcha is not displayed

### ISSUE THREAD

**Issue by JelleGe** [StudioForty9/Recaptcha#3]
Hi,

We use a CMS page for our contact form, so that we can use our own custom URL.
On this CMS page in the XML layout I added this:

< reference name="content">
  < block type="core/template" name="contactForm" template="contacts/form.phtml">
    < action method="setFormAction"><value>/contacts/index/post</value></action>
    < block type="studioforty9_recaptcha/explicit" name="studioforty9.recaptcha.explicit" template="studioforty9/recaptcha/explicit.phtml">
      < action method="setAllow"><value>true</value></action>
    </ block>
  </ block>
</ reference>

In our custom form.phtml file I added this line at the bottom:
    <?php echo $this->getChildHtml('studioforty9.recaptcha.autorender'); ?>

And off course in the extention settings I enabled the extention and also the contact form.

What am I doing wrong?

**Comment by studioforty9-dev** [comment]
Hi, 

It looks like your code sample is incomplete, so it's difficult for me to say.

Can you please edit and make sure you prefix ```xml and suffix with ```.

Are you using the most recent version v1.2.0?

**Comment by JelleGe** [comment]
Sorry my mistake! Got the problem and it works fine now. Thanks for your work

**Comment by studioforty9-dev** [comment]
Great, glad you're up and running.
