### ISSUE TITLE
Incorrect CAPTCHA.

### ISSUE THREAD

**Issue by DorotheeC** [StudioForty9/Recaptcha#32]
Hello,
I've activated your module on Forgot Password Form and Account Registration Form, but I always have "Incorrect CAPTCHA." error message after submitting the form.
It seems to work well with Login Form.
Can you help me?
Thanks

**Comment by colinmurphy** [comment]
Hi DorotheeC,

Can you leave us know what Magento version you are using and also can you send a screenshot of your Recaptcha settings please. 

Also have you tested this with RWD or base/default theme with no other community/local module enabled bar the recaptcha module?

Regards,
Colin

**Comment by DorotheeC** [comment]
Hi,
I have found the solution by disable the captcha option in system>configuration>clients>client configuration.
Thank you

**Comment by colinmurphy** [comment]
Thanks DorotheeC,

Regards,
Colin
