### ISSUE TITLE
is there any reason to not use this on checkout?

### ISSUE THREAD

**Issue by willboudle** [StudioForty9/Recaptcha#33]
I notice that it is not available by default, and that is where we would like to use it.

**Comment by colinmurphy** [comment]
HI willboudle,

Thank you for contacting us. The module was created by a developer who has since have left the company. I will ask him any reason why it might not of been implemented and we will get back to you over the coming days.

Regards,
Colin

**Comment by willboudle** [comment]
Thanks, I appreciate it.

**Comment by colinmurphy** [comment]
Hi willboudle,

So after talking to the developer he said that the reason why was to do with not being able to add more than re-captcha form to the checkout.  It is possible but in his words 'pretty dirty to implement'. There is however a pull request for this which you could use for reference - https://github.com/StudioForty9/Recaptcha/pull/31

He said that he had started on trying to implement this before but he ran into issues with storing window object in separate templates.

I hope this helps. If you have any further questions please leave me know.

Regards,
Colin

**Comment by TheRealJAG** [comment]
I assume it would skyrocket your cart abandonment.
