### ISSUE TITLE
"There was an error with the recaptcha code, please try again."

### ISSUE THREAD

**Issue by newyorkwebdesign** [StudioForty9/Recaptcha#34]
Running Magento Magento ver. 1.9.2.4. Installed via ftp. All looks great though when I submit form (any form), the error returns: "There was an error with the recaptcha code, please try again." The error in exception log:

`2017-03-13T17:43:21+00:00 ERR (3):
exception 'Zend_Http_Client_Adapter_Exception' with message 'Invalid chunk size "" unable to read chunked body' in /home/shop_production/htdocs/lib/Zend/Http/Client/Adapter/Socket.php:370
Stack trace:
#0 /home/shop_production/htdocs/lib/Zend/Http/Client.php(1089): Zend_Http_Client_Adapter_Socket->read()
#1 /home/shop_production/htdocs/app/code/community/Studioforty9/Recaptcha/Helper/Request.php(80): Zend_Http_Client->request()
#2 /home/shop_production/htdocs/app/code/community/Studioforty9/Recaptcha/Model/Observer.php(42): Studioforty9_Recaptcha_Helper_Request->verify()
#3 /home/shop_production/htdocs/app/code/core/Mage/Core/Model/App.php(1358): Studioforty9_Recaptcha_Model_Observer->onPostPreDispatch()
#4 /home/shop_production/htdocs/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod()
#5 /home/shop_production/htdocs/app/Mage.php(456): Mage_Core_Model_App->dispatchEvent()
#6 /home/shop_production/htdocs/app/code/local/Mage/Core/Controller/Varien/Action.php(526): Mage::dispatchEvent()
#7 /home/shop_production/htdocs/app/code/core/Mage/Core/Controller/Front/Action.php(69): Mage_Core_Controller_Varien_Action->preDispatch()
#8 /home/shop_production/htdocs/app/code/core/Mage/Contacts/controllers/IndexController.php(44): Mage_Core_Controller_Front_Action->preDispatch()
#9 /home/shop_production/htdocs/app/code/local/Mage/Core/Controller/Varien/Action.php(406): Mage_Contacts_IndexController->preDispatch()
#10 /home/shop_production/htdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch()
#11 /home/shop_production/htdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match()
#12 /home/shop_production/htdocs/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#13 /home/shop_production/htdocs/app/Mage.php(692): Mage_Core_Model_App->run()
#14 /home/shop_production/htdocs/index.php(84): Mage::run()
#15 {main}
`

I tried the fix https://github.com/StudioForty9/Recaptcha/issues/9 -- changing app/code/community/Studioforty9/Recaptcha/Helper/Request.php without luck.

BTW, No javascript or other errors appear on pages with form/s.

Any ideas?

Thanks!

**Comment by gdm** [comment]
Try to downgrade HTTP to 1.0

{code}
$client->setConfig(array(
    'httpversion' => Zend_Http_Client::HTTP_0 
));
{code}

Idea from https://robotsystematic.com/invalid-chunk-size-magento-and-hhvm

**Comment by newyorkwebdesign** [comment]
In my case, the file that was edited by gdm is: ./code/community/Studioforty9/Recaptcha/Helper/Request.php in public function verify:

`        $client = $this->getHttpClient();
        $client->setParameterPost($params);
        $client->setConfig(array( 'httpversion' => Zend_Http_Client::HTTP_0));
        $errors = array();
`

**Comment by DevendraGupta1991** [comment]
While registering new site in Google Recaptcha

Choose "Invisible reCAPTCHA" 

And Register your site. and configure newly generated Site and Secret key

it works for me
