### ISSUE TITLE
Captcha does not work

### ISSUE THREAD

**Issue by danielciornei** [StudioForty9/Recaptcha#4]
I implemented this on a website but looks like the actual checkbox does nothing. I can submit form without clicking the box as no error pops up. Looks like the form does not gothrough captcha. 
Site is www.woodandbeyond.com and it's only enabled in product reviews

**Comment by eoghanobrien** [comment]
Hi,

Which version are you running?
How did you download the extension? Magento Connect or Composer?

**Comment by danielciornei** [comment]
Hi.

Magento 1.9 

Downloaded from github today

Since i wrote the email i found that my review form does not validate at all. 

Your extension works great as tested on all the rest forms except reviews but i believe it to be unrelated with the extension.

**Comment by eoghanobrien** [comment]
Are you using a custom theme like Ultimo? Or are you using the built in review functionality, can you provide a link?

**Comment by danielciornei** [comment]
Custom theme
But like i said in my previous email. 

It.s related to the form itself. Had some jquery that screwed up the validation. All good now. Thank you

**Comment by eoghanobrien** [comment]
Okay great, it might help others to know what happened. Thanks.

**Comment by danielciornei** [comment]
No problem

What happened is that  i have a custom theme and i am using a plugin for tabs called easy tabs

at forst the block was not displayong but i solved it by following your guides and adding this in my local xml

## <catalog_product_view>

<reference name="review_tabbed">
            <block type="review/form" name="product.review.form" as="review_form">
                <block type="studioforty9_recaptcha/explicit" name="studioforty9.recaptcha.explicit" template="studioforty9/recaptcha/explicit.phtml">
                <action method="setAllow"><value>true</value></action>
                </block>
                 <block type="page/html_wrapper" name="product.review.form.fields.before" as="form_fields_before" translate="label">
                    <label>Review Form Fields Before</label>
                    <action method="setMayBeInvisible"><value>1</value></action>
                </block>
            </block>
        </reference>
——
</catalog_product_view>

all good so far except my form would not validate. whenever o clicked on an empty form even… would refresh and tell me that nickname was required and so on. but captcha was not in this list

so i had a look at the original rwd form file and i found out that i was displaying the rating stars a bit wrong and had a jquery in that file for this. which broke the validation. 

now i can see the validation works as intended and the forms light up in red when i click on send review on an empty form.

**Comment by eoghanobrien** [comment]
Great, nice sleuthing :) hopefully it will help anyone who has s similar issue! Thanks for taking the time to explain.
