### ISSUE TITLE
Ultimo Theme, followed instructions, review Captcha not showing

### ISSUE THREAD

**Issue by GTWarehouse** [StudioForty9/Recaptcha#7]
As per the title, have followed the instructions carefully, and cannot get the captcha box to show under the reviews tab using the Ultimo theme. HELP!

**Comment by eoghanobrien** [comment]
It's difficult to suggest a solution without knowing which other extensions you have installed or what's going on in your local.xml (there's a known conflict with the Ebizmarts_MageMonkey extension, there's a fix for that in the readme file). If you would like further support please contact magento at studioforty dot com
